/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package net.scrain.aoc

import spock.lang.Specification

class AdventTests extends Specification {
    def "Verify Day01"() {
        expect:
            Day01.getPart1Result(filename) == expectedPart1
            Day01.getPart2Result(filename) == expectedPart2

        where:
            filename            | expectedPart1 | expectedPart2
            'day01.example.txt' | 514579        | 241861950
            'day01.data.txt'    | 259716        | 120637440
    }

    def "Verify Day02"() {
        expect:
            Day02.getPart1Result(filename) == expectedPart1
            Day02.getPart2Result(filename) == expectedPart2

        where:
            filename            | expectedPart1 | expectedPart2
            'day02.example.txt' | 2             | 1
            'day02.data.txt'    | 418           | 616
    }
}
